### ISSUE TITLE
m分割によるコメント数について

### ISSUE THREAD

**Issue by yuya-painapo** [yuya-painapo/want_to#10]
自分が作成したプログラム
与える情報として動画中の一番最後のコメントの位置(1000件目のvpos)と分割数を与えている。
本来、動画の長さと分割数をあたえなくてはならない。
欲しい情報としては動画の長さをvpos値として変換することができればうれしい。
やり方がわかる人いませんか？

**Comment by hogehiga** [comment]
http://ext.nicovideo.jp/api/getthumbinfo/sm9 とかどうですか？
