### ISSUE TITLE
動画ページへのふせんが即時に反映されない

### ISSUE THREAD

**Issue by rikki-tamaki** [yuya-painapo/want_to#101]
動画ページにてふせんを付けた場合、
以前は追加したふせんが即時に表示されていたが、
現在は即時に表示されず、更新後に表示されるようになっている。
ex) http://niconico-highlight.herokuapp.com/home/movie/sm9

**Comment by yuyan7** [comment]
#102 で修正し、正常に動作することを確認したためクローズします。
