### ISSUE TITLE
config/initializer/niconico.rb を編集した時に、Railsを再起動しないと反映されなくて辛い

### ISSUE THREAD

**Issue by hogehiga** [yuya-painapo/want_to#14]
Railsを再起動しなくても反映されるように出来ないでしょうか？(ApplicationControllerあたりに書くと良さそう？)

**Comment by taikione** [comment]
了解です。initializerに書いてるので、home_controller.rb の方に移植しましたー。

**Comment by hogehiga** [comment]
:+1:
