### ISSUE TITLE
glyphiconsが表示されない

### ISSUE THREAD

**Issue by yuyan7** [yuya-painapo/want_to#19]
glyphiconsが表示されません！
railsだと特別な方法を使わないといけない？

**Comment by hogehiga** [comment]
すみません、glyphiconsってなんですか？

**Comment by yuyan7** [comment]
http://bootstrap3.cyberlab.info/components/glyphicons.html
こんな感じのアイコン？みたいなやつです。

**Comment by hogehiga** [comment]
このへんとか参考になります？(雑)
http://qiita.com/onjiro/items/809dbc3c61b1fa576b26

**Comment by yuyan7** [comment]
参考になりました。
１、フォントを precompileを実施し、bootstrap.cssをbootstrap.css.erbにし、
url(<%= asset_path("...") %>)をつけることで表示されることを確認しました。
情報ありがとうございます。

**Comment by hogehiga** [comment]
herokuでも表示されることを確認しましたのでクローズします。
