### ISSUE TITLE
デプロイできません！

### ISSUE THREAD

**Issue by yuyan7** [yuya-painapo/want_to#21]
TravisCIでデプロイしようとした時にエラーが発生しデプロイできません。

**Comment by yuyan7** [comment]
デプロイ時に
Precompiling assets failed.
というエラーメッセージが表示される

**Comment by hogehiga** [comment]
Travis-CIでテストが通ったら自動でHerokuにデプロイするように設定されてます。
現象が発生した時のログはこちら→ https://travis-ci.org/yuya-painapo/want_to/builds/85319759

期待される結果は、デプロイができる、です。

**Comment by yuyan7** [comment]
pull requests#22
自分のherokuでデプロイができることを確認しました。

**Comment by yuyan7** [comment]
Mergeされデプロイされたのでクローズとさせていただきます。
