### ISSUE TITLE
トップ画面の検索欄にsm9と入力し、検索ボタンを押下した後30秒待ってもページが遷移しない

### ISSUE THREAD

**Issue by hogehiga** [yuya-painapo/want_to#24]
# 再現手順
1. http://infinite-plateau-1767.herokuapp.com/ にアクセスする。
2. 検索欄にsm9を入力する。
3. 検索ボタンを押下した後30秒待つ。
# 期待される結果

http://infinite-plateau-1767.herokuapp.com/home/movie/sm9 にアクセスした時と同じような画面が表示される。
# 実際の結果

ページが遷移しない。

**Comment by taikione** [comment]
自分のプルリクがマージされると、検索されるようになると思います。

**Comment by hogehiga** [comment]
了解しました。
