### ISSUE TITLE
niconicoについて

### ISSUE THREAD

**Issue by taikione** [yuya-painapo/want_to#3]
動画のコメントに時間情報がついていない。
プレミアム会員限定？
今回は、http://msg.nicovideo.jp/10/api/thread?version=20090904&thread=1173108780&res_from=-100 を投げて帰ったきたものを使ってるが、dateがあるけれども、動画の時間に対する情報があるのか不明。

課題としては、
- [ ] コメントの時間情報が取得可能か調べる
- [ ] コメントが取れない動画の調査(感覚だと新しめのものはエラーになる?)

気づいた事があれば適宜追加していく。

**Comment by taikione** [comment]
DIE 問題が。
http://blog.mikumiku.moe/blog/2014/08/nicothumbwatch4html5-howtowork.html より

ニコニコ動画の再生画面の共有ボタンにある、外部プレイヤーのHTMLを使って今は表示している。こんな感じで。

```
<script type="text/javascript" src="http://ext.nicovideo.jp/thumb_watch/sm9"></script>
<noscript><a href="http://www.nicovideo.jp/watch/sm9">【ニコニコ動画】新・豪血寺一族 -煩悩解放 - レッツゴー！陰陽師</a></noscript>
```

このHTMLを貼った場所に外部プレイヤーができる。
ちなみに，Flashが使えない環境では動画へのリンクが張られる。
このスクリプトは色々対策されていて、最初から貼っていないと動かない。
後からJavascriptで追加しても動かない。また，iframe内でも動かない。

---

とのことで、ローカルでは動いてるけど、heroku上だと動画が表示されない。おうふ

**Comment by hogehiga** [comment]
こっち側でいろいろコントロールしやすくなるので、iframeを使って表示させてみようと思ったら表示できなかったんですけど、そういうことなんですね……

**Comment by taikione** [comment]
表示できたり、できなかったり環境で変わるんですかね。自分の場合は、表示できてました。たまたまかもしれませんが

**Comment by hogehiga** [comment]
> コメントの時間情報が取得可能か調べる

http://www.nicovideo.jp/watch/sm9 のコメント欄から推測すると、コメント欄の再生時という項目が、そのコメントが動画のどのタイミングで投稿されたのかを表す値っぽいです。
http://msg.nicovideo.jp/10/api/thread?version=20090904&thread=1173108780&res_from=-100 から返って来た結果と、 http://www.nicovideo.jp/watch/sm9 のコメント欄の再生時を見比べると、 `/packet/chat/@vpos` に1/100を掛けた値が、再生時を秒に変換した値に近いっぽいです(多分`@vpos`を丸めて再生時を表現するのに使ってるのかな)。

**Comment by hogehiga** [comment]
>  コメントが取れない動画の調査(感覚だと新しめのものはエラーになる?)

新しめというのがどの程度新しいのか不明ですが、公式で用意されている[スナップショット検索API](http://search.nicovideo.jp/docs/api/snapshot.html)だと

> 検索結果は、毎日AM5:00に保存された情報から返されます。

となっています。
もしかしたらスナップショット検索API以外のAPIも、毎日AM5:00に保存された情報から返すという決まりなのかもしれません。

ぱっとしませんが以上もしかしたら情報です。

**Comment by taikione** [comment]
IE10で表示できない問題。おうふ。

**Comment by taikione** [comment]
-- 取得できない、できる動画について

実行日 : 2015年10月07日 22:52
取得できない動画、取得できる動画が存在する問題について
記録として。ok = 取得可能、 ng = 取得失敗

sm27307176 2015年10月06日 03時35分 投稿 ok 再生91194
sm27308105 2015年10月06日 15時50分 投稿 ng
sm27310205 2015年10月06日 17時59分 投稿 ng 再生40 再生時間2:33
sm27310428 2015年10月06日 18時34分 投稿 ng 再生30
sm27311303 2015年10月06日 20時52分 投稿 ng 再生139 再生時間10:19
sm27312353 2015年10月06日 22時34分 投稿 ok 再生77
sm27313597 2015年10月07日 00時50分 投稿 ok 再生233
sm27313606 2015年10月07日 00時51分 投稿 ng
sm27317596 2015年10月07日 22時00分 投稿 ok 再生22

**Comment by hogehiga** [comment]
>  コメントが取れない動画の調査(感覚だと新しめのものはエラーになる?)

について。

sm27308105のコメントですが、http://nmsg.nicovideo.jp/api/thread?version=20090904&thread=1444114237&res_from=-100で取得できました。
http://flapi.nicovideo.jp/api/getflv/sm* を叩いた時に帰ってくるmsパラメータの値で、どこのサーバーにコメントを取りに行けばいいのか判定できると思います。

**Comment by taikione** [comment]
コメントありうございます。動画によって、

http://nmsg.nicovideo.jp/api/thread?version=2009090 みたいな形式と
http://msg.nicovideo.jp/5/api/thread?version=20061206 の二通りの取得方法があるみたいですね。

コメント見て気が付きました。修正しますす！！！１

**Comment by hogehiga** [comment]
本筋とは関係ないですが。。。 

Issueが長くなると後から追うのが大変になります。
このIssueであがっている

> コメントの時間情報が取得可能か調べる
> コメントが取れない動画の調査(感覚だと新しめのものはエラーになる?)

が解決したら一旦このIssueは閉じるのが良いかと思います。

**Comment by taikione** [comment]
動画によって、
- http://nmsg.nicovideo.jp/api/*
- http://msg.nicovideo.jp/5/api/*  
  のどちらか適切な方を使うように変更しました。

> -- 取得できない、できる動画について
> sm27308105 2015年10月06日 15時50分 投稿 ng
> sm27310205 2015年10月06日 17時59分 投稿 ng 再生40 再生時間2:33
> sm27310428 2015年10月06日 18時34分 投稿 ng 再生30
> sm27311303 2015年10月06日 20時52分 投稿 ng 再生139 再生時間10:19
> sm27313606 2015年10月07日 00時51分 投稿 ng

の取得できなかった動画は、取得可能になっています。
コメントの時間情報についても vpos から取得可能と解決済みです。
