### ISSUE TITLE
Topページを検索窓と再生ボタンだけにするのはどうでしょうか。

### ISSUE THREAD

**Issue by hogehiga** [yuya-painapo/want_to#43]
トップページのniconico highlight(仮)、高まった図は必要ない説があります。
topは検索窓と再生ボタンだけにするのはどうでしょうか。
ページの要素が少ないほど、何をしていいのか迷わなくてすむと思います。

**Comment by yuyan7** [comment]
変更してください。
作ってみないとどっちがいいよね、っていう話ができないので、、、
案があれば(イメージでもいいので)作ってみてデモして議論しましょう。

**Comment by yuyan7** [comment]
<img width="1280" alt="2015-10-22 22 54 54" src="https://cloud.githubusercontent.com/assets/8910941/10667018/10b0fed4-7910-11e5-9a92-3acbc60ba419.png">

**Comment by yuyan7** [comment]
何もないバージョン
<img width="1280" alt="2015-10-22 22 59 21" src="https://cloud.githubusercontent.com/assets/8910941/10667111/8fc3b0cc-7910-11e5-8789-64e332acbc0c.png">

**Comment by yuyan7** [comment]
これがいいかも？
グーグルっぽい
<img width="1280" alt="2015-10-22 23 01 36" src="https://cloud.githubusercontent.com/assets/8910941/10667164/de158534-7910-11e5-966e-8a1d83c7ac8d.png">

**Comment by taikione** [comment]
かなりシンプルですね。確かにgoogle感あるかもしれない

**Comment by yuyan7** [comment]
だけど本当に何なのかわからないかも

**Comment by taikione** [comment]
最後に何が得られるのか、とか分かるようにしないといけないですよね。
水曜日に話してて出た案なので、再度、土曜日に集まった時にnakamuraさん達含め話し合いたいです。

**Comment by yuyan7** [comment]
トップページが変更されたのでクローズします。
