### ISSUE TITLE
link_toで home/movie/sm9 で動画が再生されない問題

### ISSUE THREAD

**Issue by taikione** [yuya-painapo/want_to#54]
viewの中で、link_to などで動画再生ページ(movie)にジャンプすると、動画が表示されない問題が発生

トレンドタグを押すと、そのタグで検索します。
<img width="429" alt="2015-10-28 20 58 47" src="https://cloud.githubusercontent.com/assets/13164940/10787873/19dee812-7db7-11e5-9980-01b7aadeae6e.png">

sm188023 と動画IDは取得できているようですが、動画が表示されません。
<img width="429" alt="2015-10-28 20 59 01" src="https://cloud.githubusercontent.com/assets/13164940/10787874/1bb44682-7db7-11e5-8ff4-46d66ada941f.png">

リロードすると動画が出てきます。
<img width="429" alt="2015-10-28 20 59 07" src="https://cloud.githubusercontent.com/assets/13164940/10787875/1d4dcab8-7db7-11e5-8145-1e89c4ef9b1b.png">

**Comment by hogehiga** [comment]
多分原因は以下の2つの事柄が絡んでいると思います。
- turbolinksを使っている。
- ニコニコ動画の外部プレイヤーはあとからDOMを書き換えて追加した場合には無効になる。

**Comment by taikione** [comment]
http://kray.jp/blog/must-know-about-turbolinks/ を参考に、
`<a href="/home/movie/sm9" data-no-turbolink="1">sm9</a>` で ページ遷移時にturbolinksを無効にすると一応動画が表示されます。がページの表示が遅くなります。
こんな感じですhttps://github.com/taikione/want_to/commit/22daf81886eced57bc22c261f5b90571390bc31c のindex.html.erb

**Comment by taikione** [comment]
turbolinksを無効にする方法ってあまり良くないのでしょうか？

**Comment by hogehiga** [comment]
個人的には
- ニコニコ動画の外部プレイヤーのように他にも相性悪いものがあるかもしれないのを、いちいち考慮するのがめんどくさい(原因を特定するのがだるい不具合が発生しそう)。
- サーバサイドの処理が軽減するわけではない(TurbolinksはCSS/JavaScriptの再パースを抑制するだけなので)。
- ページ読み込みのクルクルが無くなるのは、ユーザーが今自分がどういう状態に置かれているのかわからない(読み込みに時間がかかっているのか、クリックをミスったのかわかりにくい)ので良くない気がする。

っていうのがあるので、むしろ全体的に無効にしたいではあります。。。。。っていうのは古い考え方なのかしらん。。。

**Comment by taikione** [comment]
@hogehiga ありがとうございます。

> ニコニコ動画の外部プレイヤーのように他にも相性悪いものがあるかもしれないのを、いちいち考慮するのがめんどくさい(原因を特定するのがだるい不具合が発生しそう)。
> サーバサイドの処理が軽減するわけではない(TurbolinksはCSS/JavaScriptの再パースを抑制するだけなので)。
> ページ読み込みのクルクルが無くなるのは、ユーザーが今自分がどういう状態に置かれているのかわからない(読み込みに時間がかかっているのか、クリックをミスったのかわかりにくい)ので良くない気がする。

なるほど。 外部プレイヤーに関しては同感です。相性が悪そうですよね。
古い考えなのか、っていうのは僕からは何とも...おうふ :disappointed:

**Comment by taikione** [comment]
現時点ではリロードしないと外部プレイヤーが表示されないので、とりあえず、トレンドタグから動画再生する場合にのみturbolinksを無効にした設定のブランチをプルリク送りたいのですが、良いでしょうか？

**Comment by hogehiga** [comment]
- 土曜のレビューにはリロードしなくても外部プレイヤーが表示されて欲しい
- turbolinksを全体的に有効にするか無効にするかの話し合いするのは、どんなに早くても土曜の午後になりそう

ってのを考えると、とりあえずで送ってもいい気がします。
あとついでに、トップのエキサイティンな画像をクリックした時も外部プレイヤーが表示されるようにしてもらえるとなおいいと思います。

**Comment by taikione** [comment]
土曜or来週水曜日に集まった時に是非話し合いたいです。
レビューの時に外部プレイヤーが表示されないとすこし残念なので、エキサイティンな画像の件も修正してプルリクエスト送りたいと思います！！！

**Comment by hogehiga** [comment]
#59 で暫定対処済み。

**Comment by hogehiga** [comment]
とりあえず暫定対処で行くことになったのでCloseします。
