### ISSUE TITLE
ブロックごとのコメント数とグラフの数字に齟齬がある。

### ISSUE THREAD

**Issue by hogehiga** [yuya-painapo/want_to#60]
# 再現手順

ローカルでアプリを動かして、 /home/movie/sm236499 にアクセスする。
# 実際の結果

![2015-10-30 10 41 06](https://cloud.githubusercontent.com/assets/6975731/10836594/d3f260b2-7ef2-11e5-80e0-5bcb6e10d3c3.png)
# 期待される結果

右から4つ目のグラフの高さが、デバッグ出力の数字(この画像の場合は168)と同じであること。

**Comment by yuyan7** [comment]
#70 にて修正されたためクローズします。
