### ISSUE TITLE
トレンドタグをクリックしても画面遷移できない

### ISSUE THREAD

**Issue by yuyan7** [yuya-painapo/want_to#89]
自分の環境だけかもしれませんがトレンドタグをクリックしても動画再生画面に遷移できません。

再現方法
トレンドタグをどれか一つクリックする。

<img width="1280" alt="2015-11-19 1 36 57" src="https://cloud.githubusercontent.com/assets/8910941/11247129/1917ab5a-8e5e-11e5-80a9-93f99373d246.png">
エラー画面

"/" のバグ修正した時に起こっている？

**Comment by hogehiga** [comment]
現象の再現を確認しました。対応してみます。
